# Generated by Django 4.1.1 on 2022-12-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
