# Generated by Django 4.1.1 on 2022-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_alter_users_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateround',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='candidateround',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidateround',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
