# Generated by Django 4.1.1 on 2022-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_alter_candidateround_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='enrollment_no',
            field=models.IntegerField(unique=True),
        ),
    ]
