# Generated by Django 4.1.1 on 2022-11-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_alter_candidates_cg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='cg',
            field=models.IntegerField(),
        ),
    ]
