# Generated by Django 4.1.1 on 2022-11-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_alter_candidates_cg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateround',
            name='interview_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.interviewpanel'),
        ),
        migrations.AlterField(
            model_name='candidateround',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateround',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_notified', 'Not Notified'), ('notified', 'Notified'), ('waiting_room', 'In Waiting Room'), ('interview', 'In Interview'), ('done', 'Done')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='candidateround',
            name='time_slot',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='candidateround',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
