# Generated by Django 4.1.1 on 2022-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_alter_candidateround_interview_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemarks',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
